version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mydb1
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: backend_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=mydb1
      - DB_USER=root
      - DB_PASSWORD=123456
    ports:
      - "5001:5000"
    networks:
      - app_network
    volumes:
      - ./backend:/app

  frontend:
    build: ./fronted/for-contaner-with-yml
    container_name: frontend_app
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app_network
    volumes:
      - ./fronted/for-contaner-with-yml:/app
    environment:
      - REACT_APP_API_URL=http://localhost:5001
volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
